name: Deploy Next.js (standalone) to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Prepare standalone output
        run: |
          mkdir -p ./.next/standalone/.next
          cp -r ./public ./.next/standalone/public
          cp -r ./.next/static ./.next/standalone/.next/static

      - name: Preflight: check publish profile secret exists
        run: |
          if [ -z "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75861A4883F84CE68C50828C6F14174C }}" ]; then
            echo "Publish profile secret is EMPTY or not visible to this workflow."; exit 1;
          fi

      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-002-gen10-step3-2-node-oshima3
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75861A4883F84CE68C50828C6F14174C }}
          package: ./.next/standalone
